<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg width="180px" src=<?php include "./assets/logos/logo_kingdom_horiz.svg"; ?> </svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pesquisar</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Relatorios</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">ADM</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <button onclick="window.location.href = './login.php'" type="button" class="btn btn-outline-primary me-2">Entrar</button>
        <button onclick="window.location.href = './registre.php'" type="button" class="btn btn-primary">Registre-se</button>
      </div>
    </header>
</div>